/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appeal {
  'id' : bigint,
  'owner' : Principal,
  'createdTime' : bigint,
  'platform' : Platform,
  'userExplanation' : string,
  'reasonCategory' : ReasonCategory,
  'generatedText' : string,
  'evidenceIds' : Array<bigint>,
}
export interface CollectiveReport {
  'region' : Region,
  'neighborhood' : string,
  'platform' : Platform,
  'timestamp' : Time,
  'reason' : ReasonCategory,
}
export interface Evidence {
  'id' : bigint,
  'regiao' : [] | [Region],
  'owner' : Principal,
  'bairro' : [] | [string],
  'platform' : [] | [Platform],
  'notes' : string,
  'uploadTime' : bigint,
  'evidenceType' : EvidenceType,
}
export type EvidenceType = { 'selfie' : null } |
  { 'screenshot' : null };
export interface LossProfile {
  'dailyEarnings' : number,
  'deactivationDate' : bigint,
  'platform' : Platform,
  'daysPerWeek' : bigint,
}
export type Platform = { 'uber' : null } |
  { 'ninetyNine' : null } |
  { 'ifood' : null } |
  { 'rappi' : null };
export type Principal = Principal;
export interface PublicLossProfile {
  'dailyEarnings' : number,
  'deactivationDate' : bigint,
  'platform' : Platform,
  'daysPerWeek' : bigint,
}
export type ReasonCategory = { 'lowRating' : null } |
  { 'other' : null } |
  { 'documentsExpired' : null } |
  { 'fraudSuspicion' : null } |
  { 'selfieInvalid' : null } |
  { 'dangerousConduct' : null } |
  { 'multipleAccounts' : null };
export type Region = { 'maracanau' : null } |
  { 'caucaia' : null } |
  { 'fortaleza' : null };
export type SubscriptionPlan = { 'free_24h' : null } |
  { 'pro_monthly' : null } |
  { 'pro_annual' : null };
export interface SubscriptionStatus {
  'startTime' : [] | [bigint],
  'endTime' : [] | [bigint],
  'currentPlan' : SubscriptionPlan,
}
export type Time = bigint;
export interface UserAccessInfo {
  'principal' : Principal,
  'isBlockedByAdmin' : boolean,
  'subscriptionStatus' : SubscriptionStatus,
  'profile' : [] | [UserProfile],
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WeatherCondition = { 'cloudy' : null } |
  { 'clear' : null } |
  { 'nublado' : null } |
  { 'soleado' : null } |
  { 'tempestuoso' : null } |
  { 'windy' : null } |
  { 'rainy' : null };
export interface WeatherSample {
  'city' : string,
  'timestamp' : Time,
  'temperatureC' : number,
  'condition' : WeatherCondition,
}
export interface WorkSession {
  'id' : bigint,
  'startTime' : Time,
  'endTime' : [] | [Time],
  'owner' : Principal,
  'city' : string,
  'weatherSamples' : Array<WeatherSample>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWeatherSample' : ActorMethod<
    [bigint, { 'temperatureC' : number, 'condition' : WeatherCondition }],
    WorkSession
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createEvidence' : ActorMethod<
    [
      {
        'regiao' : [] | [Region],
        'bairro' : [] | [string],
        'platform' : [] | [Platform],
        'notes' : string,
        'evidenceType' : EvidenceType,
      },
    ],
    Evidence
  >,
  'endWorkSession' : ActorMethod<[bigint], WorkSession>,
  'generateAppeal' : ActorMethod<
    [
      {
        'platform' : Platform,
        'userExplanation' : string,
        'reasonCategory' : ReasonCategory,
        'evidenceIds' : Array<bigint>,
      },
    ],
    Appeal
  >,
  'getAllEvidence' : ActorMethod<[], Array<Evidence>>,
  'getAllUserAccessInfo' : ActorMethod<[], Array<UserAccessInfo>>,
  'getAppeal' : ActorMethod<[bigint], [] | [Appeal]>,
  'getCallerAppeals' : ActorMethod<[], Array<Appeal>>,
  'getCallerLossProfile' : ActorMethod<[], [] | [PublicLossProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollectiveReports' : ActorMethod<[], Array<CollectiveReport>>,
  'getEvidenceById' : ActorMethod<[bigint], [] | [Evidence]>,
  'getEvidenceFiltered' : ActorMethod<
    [[] | [EvidenceType], [] | [Platform]],
    Array<Evidence>
  >,
  'getLossProfile' : ActorMethod<[Principal], [] | [PublicLossProfile]>,
  'getPlatformStats' : ActorMethod<[Platform], bigint>,
  'getReasonStats' : ActorMethod<[ReasonCategory], bigint>,
  'getRegionStats' : ActorMethod<[Region], bigint>,
  'getRevisoMotivadaMessage' : ActorMethod<[], string>,
  'getSubscriptionStatus' : ActorMethod<[], SubscriptionStatus>,
  'getTimeline' : ActorMethod<
    [
      {
        'startTime' : [] | [bigint],
        'endTime' : [] | [bigint],
        'platformFilter' : [] | [Platform],
        'typeFilter' : [] | [EvidenceType],
      },
    ],
    Array<Evidence>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkSession' : ActorMethod<[bigint], [] | [WorkSession]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCurrentUserBlocked' : ActorMethod<[], boolean>,
  'logWorkSession' : ActorMethod<[{ 'city' : string }], WorkSession>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setLossProfile' : ActorMethod<[LossProfile], undefined>,
  'submitCollectiveReport' : ActorMethod<
    [
      {
        'region' : Region,
        'neighborhood' : string,
        'platform' : Platform,
        'reason' : ReasonCategory,
      },
    ],
    undefined
  >,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'upgradeSubscription' : ActorMethod<[SubscriptionPlan], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];