/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentStatus = IDL.Record({
  'status' : IDL.Text,
  'paymentId' : IDL.Text,
  'rawResponse' : IDL.Text,
});
export const SubscriptionPlan = IDL.Variant({
  'free_24h' : IDL.Null,
  'pro_monthly' : IDL.Null,
  'pro_annual' : IDL.Null,
});
export const PaymentCheckoutResponse = IDL.Record({
  'paymentId' : IDL.Text,
  'checkoutUrl' : IDL.Opt(IDL.Text),
});
export const Region = IDL.Variant({
  'maracanau' : IDL.Null,
  'caucaia' : IDL.Null,
  'fortaleza' : IDL.Null,
});
export const Principal = IDL.Principal;
export const Platform = IDL.Variant({
  'uber' : IDL.Null,
  'ninetyNine' : IDL.Null,
  'ifood' : IDL.Null,
  'rappi' : IDL.Null,
});
export const EvidenceType = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'selfie' : IDL.Null,
  'screenshot' : IDL.Null,
});
export const Evidence = IDL.Record({
  'id' : IDL.Nat,
  'regiao' : IDL.Opt(Region),
  'duration' : IDL.Opt(IDL.Nat),
  'owner' : Principal,
  'bairro' : IDL.Opt(IDL.Text),
  'audioQuality' : IDL.Opt(IDL.Text),
  'videoQuality' : IDL.Opt(IDL.Text),
  'platform' : IDL.Opt(Platform),
  'notes' : IDL.Text,
  'uploadTime' : IDL.Int,
  'evidenceType' : EvidenceType,
});
export const SubscriptionStatus = IDL.Record({
  'startTime' : IDL.Opt(IDL.Int),
  'endTime' : IDL.Opt(IDL.Int),
  'currentPlan' : SubscriptionPlan,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const UserAccessInfo = IDL.Record({
  'principal' : Principal,
  'isBlockedByAdmin' : IDL.Bool,
  'subscriptionStatus' : SubscriptionStatus,
  'profile' : IDL.Opt(UserProfile),
});
export const TestimonialStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'status' : TestimonialStatus,
  'content' : IDL.Text,
  'submitter' : Principal,
  'timestamp' : IDL.Int,
});
export const PublicPaymentProviderConfig = IDL.Record({
  'publicKey' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const PublicPaymentConfig = IDL.Record({
  'mercadoPago' : PublicPaymentProviderConfig,
});
export const Time = IDL.Int;
export const WeatherCondition = IDL.Variant({
  'cloudy' : IDL.Null,
  'clear' : IDL.Null,
  'nublado' : IDL.Null,
  'soleado' : IDL.Null,
  'tempestuoso' : IDL.Null,
  'windy' : IDL.Null,
  'rainy' : IDL.Null,
});
export const WeatherSample = IDL.Record({
  'city' : IDL.Text,
  'timestamp' : Time,
  'temperatureC' : IDL.Float64,
  'condition' : WeatherCondition,
});
export const WorkSession = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'endTime' : IDL.Opt(Time),
  'owner' : Principal,
  'city' : IDL.Text,
  'weatherSamples' : IDL.Vec(WeatherSample),
});
export const LossProfile = IDL.Record({
  'dailyEarnings' : IDL.Float64,
  'deactivationDate' : IDL.Int,
  'platform' : Platform,
  'daysPerWeek' : IDL.Nat,
});
export const PaymentProviderConfig = IDL.Record({
  'publicKey' : IDL.Text,
  'enabled' : IDL.Bool,
  'accessToken' : IDL.Text,
});
export const PaymentConfig = IDL.Record({
  'mercadoPago' : PaymentProviderConfig,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkPaymentStatus' : IDL.Func([IDL.Text], [PaymentStatus], []),
  'createMercadoPagoCheckout' : IDL.Func(
      [SubscriptionPlan],
      [PaymentCheckoutResponse],
      [],
    ),
  'createPaymentPreference' : IDL.Func(
      [SubscriptionPlan],
      [PaymentCheckoutResponse],
      [],
    ),
  'getAllEvidence' : IDL.Func([], [IDL.Vec(Evidence)], ['query']),
  'getAllUserAccessInfo' : IDL.Func([], [IDL.Vec(UserAccessInfo)], ['query']),
  'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getPublicPaymentConfig' : IDL.Func([], [PublicPaymentConfig], ['query']),
  'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkSession' : IDL.Func(
      [IDL.Record({ 'city' : IDL.Text })],
      [WorkSession],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setLossProfile' : IDL.Func([LossProfile], [], []),
  'setPaymentConfig' : IDL.Func([PaymentConfig], [], []),
  'submitTestimonial' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateTestimonialStatus' : IDL.Func([IDL.Nat, TestimonialStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentStatus = IDL.Record({
    'status' : IDL.Text,
    'paymentId' : IDL.Text,
    'rawResponse' : IDL.Text,
  });
  const SubscriptionPlan = IDL.Variant({
    'free_24h' : IDL.Null,
    'pro_monthly' : IDL.Null,
    'pro_annual' : IDL.Null,
  });
  const PaymentCheckoutResponse = IDL.Record({
    'paymentId' : IDL.Text,
    'checkoutUrl' : IDL.Opt(IDL.Text),
  });
  const Region = IDL.Variant({
    'maracanau' : IDL.Null,
    'caucaia' : IDL.Null,
    'fortaleza' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const Platform = IDL.Variant({
    'uber' : IDL.Null,
    'ninetyNine' : IDL.Null,
    'ifood' : IDL.Null,
    'rappi' : IDL.Null,
  });
  const EvidenceType = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'selfie' : IDL.Null,
    'screenshot' : IDL.Null,
  });
  const Evidence = IDL.Record({
    'id' : IDL.Nat,
    'regiao' : IDL.Opt(Region),
    'duration' : IDL.Opt(IDL.Nat),
    'owner' : Principal,
    'bairro' : IDL.Opt(IDL.Text),
    'audioQuality' : IDL.Opt(IDL.Text),
    'videoQuality' : IDL.Opt(IDL.Text),
    'platform' : IDL.Opt(Platform),
    'notes' : IDL.Text,
    'uploadTime' : IDL.Int,
    'evidenceType' : EvidenceType,
  });
  const SubscriptionStatus = IDL.Record({
    'startTime' : IDL.Opt(IDL.Int),
    'endTime' : IDL.Opt(IDL.Int),
    'currentPlan' : SubscriptionPlan,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const UserAccessInfo = IDL.Record({
    'principal' : Principal,
    'isBlockedByAdmin' : IDL.Bool,
    'subscriptionStatus' : SubscriptionStatus,
    'profile' : IDL.Opt(UserProfile),
  });
  const TestimonialStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'status' : TestimonialStatus,
    'content' : IDL.Text,
    'submitter' : Principal,
    'timestamp' : IDL.Int,
  });
  const PublicPaymentProviderConfig = IDL.Record({
    'publicKey' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const PublicPaymentConfig = IDL.Record({
    'mercadoPago' : PublicPaymentProviderConfig,
  });
  const Time = IDL.Int;
  const WeatherCondition = IDL.Variant({
    'cloudy' : IDL.Null,
    'clear' : IDL.Null,
    'nublado' : IDL.Null,
    'soleado' : IDL.Null,
    'tempestuoso' : IDL.Null,
    'windy' : IDL.Null,
    'rainy' : IDL.Null,
  });
  const WeatherSample = IDL.Record({
    'city' : IDL.Text,
    'timestamp' : Time,
    'temperatureC' : IDL.Float64,
    'condition' : WeatherCondition,
  });
  const WorkSession = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'endTime' : IDL.Opt(Time),
    'owner' : Principal,
    'city' : IDL.Text,
    'weatherSamples' : IDL.Vec(WeatherSample),
  });
  const LossProfile = IDL.Record({
    'dailyEarnings' : IDL.Float64,
    'deactivationDate' : IDL.Int,
    'platform' : Platform,
    'daysPerWeek' : IDL.Nat,
  });
  const PaymentProviderConfig = IDL.Record({
    'publicKey' : IDL.Text,
    'enabled' : IDL.Bool,
    'accessToken' : IDL.Text,
  });
  const PaymentConfig = IDL.Record({ 'mercadoPago' : PaymentProviderConfig });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkPaymentStatus' : IDL.Func([IDL.Text], [PaymentStatus], []),
    'createMercadoPagoCheckout' : IDL.Func(
        [SubscriptionPlan],
        [PaymentCheckoutResponse],
        [],
      ),
    'createPaymentPreference' : IDL.Func(
        [SubscriptionPlan],
        [PaymentCheckoutResponse],
        [],
      ),
    'getAllEvidence' : IDL.Func([], [IDL.Vec(Evidence)], ['query']),
    'getAllUserAccessInfo' : IDL.Func([], [IDL.Vec(UserAccessInfo)], ['query']),
    'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getPublicPaymentConfig' : IDL.Func([], [PublicPaymentConfig], ['query']),
    'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkSession' : IDL.Func(
        [IDL.Record({ 'city' : IDL.Text })],
        [WorkSession],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setLossProfile' : IDL.Func([LossProfile], [], []),
    'setPaymentConfig' : IDL.Func([PaymentConfig], [], []),
    'submitTestimonial' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateTestimonialStatus' : IDL.Func([IDL.Nat, TestimonialStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };