/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Region = IDL.Variant({
  'maracanau' : IDL.Null,
  'caucaia' : IDL.Null,
  'fortaleza' : IDL.Null,
});
export const Platform = IDL.Variant({
  'uber' : IDL.Null,
  'ninetyNine' : IDL.Null,
  'ifood' : IDL.Null,
  'rappi' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'region' : IDL.Opt(Region),
  'name' : IDL.Text,
  'platform' : IDL.Opt(Platform),
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const PagBankReturnWebhookUrlConfig = IDL.Record({
  'returnUrl' : IDL.Text,
  'webhookUrl' : IDL.Text,
});
export const PagBankTransparentCheckoutConfig = IDL.Record({
  'token' : IDL.Text,
  'publicKey' : IDL.Text,
  'maxInstallments' : IDL.Nat,
  'email' : IDL.Text,
  'interestRate' : IDL.Opt(IDL.Float64),
  'acceptedPaymentTypes' : IDL.Vec(IDL.Text),
});
export const PublicPaymentProviderConfig = IDL.Record({ 'enabled' : IDL.Bool });
export const PublicPagBankConfig = IDL.Record({ 'enabled' : IDL.Bool });
export const PublicPaymentConfig = IDL.Record({
  'gatewayProvider' : PublicPaymentProviderConfig,
  'pagbankProvider' : PublicPagBankConfig,
});
export const Principal = IDL.Principal;
export const PagBankWebhookPayload = IDL.Record({
  'status' : IDL.Text,
  'signature' : IDL.Text,
  'paymentId' : IDL.Text,
  'rawData' : IDL.Text,
});
export const Time = IDL.Int;
export const WeatherCondition = IDL.Variant({
  'cloudy' : IDL.Null,
  'clear' : IDL.Null,
  'nublado' : IDL.Null,
  'soleado' : IDL.Null,
  'tempestuoso' : IDL.Null,
  'windy' : IDL.Null,
  'rainy' : IDL.Null,
});
export const WeatherSample = IDL.Record({
  'city' : IDL.Text,
  'timestamp' : Time,
  'temperatureC' : IDL.Float64,
  'condition' : WeatherCondition,
});
export const WorkSession = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'endTime' : IDL.Opt(Time),
  'owner' : Principal,
  'city' : IDL.Text,
  'weatherSamples' : IDL.Vec(WeatherSample),
});
export const LossProfile = IDL.Record({
  'dailyEarnings' : IDL.Float64,
  'deactivationDate' : IDL.Int,
  'platform' : Platform,
  'daysPerWeek' : IDL.Nat,
});
export const PaymentProviderConfig = IDL.Record({ 'enabled' : IDL.Bool });
export const PagBankConfig = IDL.Record({
  'webhookSecret' : IDL.Opt(IDL.Text),
  'clientId' : IDL.Opt(IDL.Text),
  'merchantId' : IDL.Opt(IDL.Text),
  'enabled' : IDL.Bool,
  'clientSecret' : IDL.Opt(IDL.Text),
});
export const PaymentConfig = IDL.Record({
  'gatewayProvider' : PaymentProviderConfig,
  'pagbankProvider' : PagBankConfig,
});
export const TestimonialStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPagBankReturnWebhookUrls' : IDL.Func(
      [],
      [IDL.Opt(PagBankReturnWebhookUrlConfig)],
      ['query'],
    ),
  'getPagBankTransparentCheckoutConfig' : IDL.Func(
      [],
      [IDL.Opt(PagBankTransparentCheckoutConfig)],
      ['query'],
    ),
  'getPublicPaymentConfig' : IDL.Func([], [PublicPaymentConfig], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'handlePagBankWebhook' : IDL.Func([PagBankWebhookPayload], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkSession' : IDL.Func(
      [IDL.Record({ 'city' : IDL.Text })],
      [WorkSession],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setLossProfile' : IDL.Func([LossProfile], [], []),
  'setPagBankReturnWebhookUrls' : IDL.Func(
      [PagBankReturnWebhookUrlConfig],
      [],
      [],
    ),
  'setPagBankTransparentCheckoutConfig' : IDL.Func(
      [PagBankTransparentCheckoutConfig],
      [],
      [],
    ),
  'setPaymentConfig' : IDL.Func([PaymentConfig], [], []),
  'submitTestimonial' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'updateTestimonialStatus' : IDL.Func([IDL.Nat, TestimonialStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Region = IDL.Variant({
    'maracanau' : IDL.Null,
    'caucaia' : IDL.Null,
    'fortaleza' : IDL.Null,
  });
  const Platform = IDL.Variant({
    'uber' : IDL.Null,
    'ninetyNine' : IDL.Null,
    'ifood' : IDL.Null,
    'rappi' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'region' : IDL.Opt(Region),
    'name' : IDL.Text,
    'platform' : IDL.Opt(Platform),
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const PagBankReturnWebhookUrlConfig = IDL.Record({
    'returnUrl' : IDL.Text,
    'webhookUrl' : IDL.Text,
  });
  const PagBankTransparentCheckoutConfig = IDL.Record({
    'token' : IDL.Text,
    'publicKey' : IDL.Text,
    'maxInstallments' : IDL.Nat,
    'email' : IDL.Text,
    'interestRate' : IDL.Opt(IDL.Float64),
    'acceptedPaymentTypes' : IDL.Vec(IDL.Text),
  });
  const PublicPaymentProviderConfig = IDL.Record({ 'enabled' : IDL.Bool });
  const PublicPagBankConfig = IDL.Record({ 'enabled' : IDL.Bool });
  const PublicPaymentConfig = IDL.Record({
    'gatewayProvider' : PublicPaymentProviderConfig,
    'pagbankProvider' : PublicPagBankConfig,
  });
  const Principal = IDL.Principal;
  const PagBankWebhookPayload = IDL.Record({
    'status' : IDL.Text,
    'signature' : IDL.Text,
    'paymentId' : IDL.Text,
    'rawData' : IDL.Text,
  });
  const Time = IDL.Int;
  const WeatherCondition = IDL.Variant({
    'cloudy' : IDL.Null,
    'clear' : IDL.Null,
    'nublado' : IDL.Null,
    'soleado' : IDL.Null,
    'tempestuoso' : IDL.Null,
    'windy' : IDL.Null,
    'rainy' : IDL.Null,
  });
  const WeatherSample = IDL.Record({
    'city' : IDL.Text,
    'timestamp' : Time,
    'temperatureC' : IDL.Float64,
    'condition' : WeatherCondition,
  });
  const WorkSession = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'endTime' : IDL.Opt(Time),
    'owner' : Principal,
    'city' : IDL.Text,
    'weatherSamples' : IDL.Vec(WeatherSample),
  });
  const LossProfile = IDL.Record({
    'dailyEarnings' : IDL.Float64,
    'deactivationDate' : IDL.Int,
    'platform' : Platform,
    'daysPerWeek' : IDL.Nat,
  });
  const PaymentProviderConfig = IDL.Record({ 'enabled' : IDL.Bool });
  const PagBankConfig = IDL.Record({
    'webhookSecret' : IDL.Opt(IDL.Text),
    'clientId' : IDL.Opt(IDL.Text),
    'merchantId' : IDL.Opt(IDL.Text),
    'enabled' : IDL.Bool,
    'clientSecret' : IDL.Opt(IDL.Text),
  });
  const PaymentConfig = IDL.Record({
    'gatewayProvider' : PaymentProviderConfig,
    'pagbankProvider' : PagBankConfig,
  });
  const TestimonialStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPagBankReturnWebhookUrls' : IDL.Func(
        [],
        [IDL.Opt(PagBankReturnWebhookUrlConfig)],
        ['query'],
      ),
    'getPagBankTransparentCheckoutConfig' : IDL.Func(
        [],
        [IDL.Opt(PagBankTransparentCheckoutConfig)],
        ['query'],
      ),
    'getPublicPaymentConfig' : IDL.Func([], [PublicPaymentConfig], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'handlePagBankWebhook' : IDL.Func([PagBankWebhookPayload], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkSession' : IDL.Func(
        [IDL.Record({ 'city' : IDL.Text })],
        [WorkSession],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setLossProfile' : IDL.Func([LossProfile], [], []),
    'setPagBankReturnWebhookUrls' : IDL.Func(
        [PagBankReturnWebhookUrlConfig],
        [],
        [],
      ),
    'setPagBankTransparentCheckoutConfig' : IDL.Func(
        [PagBankTransparentCheckoutConfig],
        [],
        [],
      ),
    'setPaymentConfig' : IDL.Func([PaymentConfig], [], []),
    'submitTestimonial' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'updateTestimonialStatus' : IDL.Func([IDL.Nat, TestimonialStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };