/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WeatherCondition = IDL.Variant({
  'cloudy' : IDL.Null,
  'clear' : IDL.Null,
  'nublado' : IDL.Null,
  'soleado' : IDL.Null,
  'tempestuoso' : IDL.Null,
  'windy' : IDL.Null,
  'rainy' : IDL.Null,
});
export const Time = IDL.Int;
export const WeatherSample = IDL.Record({
  'city' : IDL.Text,
  'timestamp' : Time,
  'temperatureC' : IDL.Float64,
  'condition' : WeatherCondition,
});
export const WorkSession = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'endTime' : IDL.Opt(Time),
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'weatherSamples' : IDL.Vec(WeatherSample),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Region = IDL.Variant({
  'maracanau' : IDL.Null,
  'caucaia' : IDL.Null,
  'fortaleza' : IDL.Null,
});
export const Platform = IDL.Variant({
  'uber' : IDL.Null,
  'ninetyNine' : IDL.Null,
  'ifood' : IDL.Null,
  'rappi' : IDL.Null,
});
export const EvidenceType = IDL.Variant({
  'selfie' : IDL.Null,
  'screenshot' : IDL.Null,
});
export const Evidence = IDL.Record({
  'id' : IDL.Nat,
  'regiao' : IDL.Opt(Region),
  'owner' : IDL.Principal,
  'bairro' : IDL.Opt(IDL.Text),
  'platform' : IDL.Opt(Platform),
  'notes' : IDL.Text,
  'uploadTime' : IDL.Int,
  'evidenceType' : EvidenceType,
});
export const ReasonCategory = IDL.Variant({
  'lowRating' : IDL.Null,
  'other' : IDL.Null,
  'documentsExpired' : IDL.Null,
  'fraudSuspicion' : IDL.Null,
  'selfieInvalid' : IDL.Null,
  'dangerousConduct' : IDL.Null,
  'multipleAccounts' : IDL.Null,
});
export const Appeal = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'createdTime' : IDL.Int,
  'platform' : Platform,
  'userExplanation' : IDL.Text,
  'reasonCategory' : ReasonCategory,
  'generatedText' : IDL.Text,
  'evidenceIds' : IDL.Vec(IDL.Nat),
});
export const PublicLossProfile = IDL.Record({
  'dailyEarnings' : IDL.Float64,
  'deactivationDate' : IDL.Int,
  'platform' : Platform,
  'daysPerWeek' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const CollectiveReport = IDL.Record({
  'region' : Region,
  'neighborhood' : IDL.Text,
  'platform' : Platform,
  'timestamp' : Time,
  'reason' : ReasonCategory,
});
export const LossProfile = IDL.Record({
  'dailyEarnings' : IDL.Float64,
  'deactivationDate' : IDL.Int,
  'platform' : Platform,
  'daysPerWeek' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWeatherSample' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'temperatureC' : IDL.Float64,
          'condition' : WeatherCondition,
        }),
      ],
      [WorkSession],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvidence' : IDL.Func(
      [
        IDL.Record({
          'regiao' : IDL.Opt(Region),
          'bairro' : IDL.Opt(IDL.Text),
          'platform' : IDL.Opt(Platform),
          'notes' : IDL.Text,
          'evidenceType' : EvidenceType,
        }),
      ],
      [Evidence],
      [],
    ),
  'endWorkSession' : IDL.Func([IDL.Nat], [WorkSession], []),
  'generateAppeal' : IDL.Func(
      [
        IDL.Record({
          'platform' : Platform,
          'userExplanation' : IDL.Text,
          'reasonCategory' : ReasonCategory,
          'evidenceIds' : IDL.Vec(IDL.Nat),
        }),
      ],
      [Appeal],
      [],
    ),
  'getAllEvidence' : IDL.Func([], [IDL.Vec(Evidence)], ['query']),
  'getAppeal' : IDL.Func([IDL.Nat], [IDL.Opt(Appeal)], ['query']),
  'getCallerAppeals' : IDL.Func([], [IDL.Vec(Appeal)], ['query']),
  'getCallerLossProfile' : IDL.Func(
      [],
      [IDL.Opt(PublicLossProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectiveReports' : IDL.Func([], [IDL.Vec(CollectiveReport)], ['query']),
  'getEvidenceById' : IDL.Func([IDL.Nat], [IDL.Opt(Evidence)], ['query']),
  'getEvidenceFiltered' : IDL.Func(
      [IDL.Opt(EvidenceType), IDL.Opt(Platform)],
      [IDL.Vec(Evidence)],
      ['query'],
    ),
  'getLossProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicLossProfile)],
      ['query'],
    ),
  'getPlatformStats' : IDL.Func([Platform], [IDL.Nat], ['query']),
  'getReasonStats' : IDL.Func([ReasonCategory], [IDL.Nat], ['query']),
  'getRegionStats' : IDL.Func([Region], [IDL.Nat], ['query']),
  'getRevisoMotivadaMessage' : IDL.Func([], [IDL.Text], ['query']),
  'getTimeline' : IDL.Func(
      [
        IDL.Record({
          'startTime' : IDL.Opt(IDL.Int),
          'endTime' : IDL.Opt(IDL.Int),
          'platformFilter' : IDL.Opt(Platform),
          'typeFilter' : IDL.Opt(EvidenceType),
        }),
      ],
      [IDL.Vec(Evidence)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkSession' : IDL.Func([IDL.Nat], [IDL.Opt(WorkSession)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkSession' : IDL.Func(
      [IDL.Record({ 'city' : IDL.Text })],
      [WorkSession],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setLossProfile' : IDL.Func([LossProfile], [], []),
  'submitCollectiveReport' : IDL.Func(
      [
        IDL.Record({
          'region' : Region,
          'neighborhood' : IDL.Text,
          'platform' : Platform,
          'reason' : ReasonCategory,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WeatherCondition = IDL.Variant({
    'cloudy' : IDL.Null,
    'clear' : IDL.Null,
    'nublado' : IDL.Null,
    'soleado' : IDL.Null,
    'tempestuoso' : IDL.Null,
    'windy' : IDL.Null,
    'rainy' : IDL.Null,
  });
  const Time = IDL.Int;
  const WeatherSample = IDL.Record({
    'city' : IDL.Text,
    'timestamp' : Time,
    'temperatureC' : IDL.Float64,
    'condition' : WeatherCondition,
  });
  const WorkSession = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'endTime' : IDL.Opt(Time),
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'weatherSamples' : IDL.Vec(WeatherSample),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Region = IDL.Variant({
    'maracanau' : IDL.Null,
    'caucaia' : IDL.Null,
    'fortaleza' : IDL.Null,
  });
  const Platform = IDL.Variant({
    'uber' : IDL.Null,
    'ninetyNine' : IDL.Null,
    'ifood' : IDL.Null,
    'rappi' : IDL.Null,
  });
  const EvidenceType = IDL.Variant({
    'selfie' : IDL.Null,
    'screenshot' : IDL.Null,
  });
  const Evidence = IDL.Record({
    'id' : IDL.Nat,
    'regiao' : IDL.Opt(Region),
    'owner' : IDL.Principal,
    'bairro' : IDL.Opt(IDL.Text),
    'platform' : IDL.Opt(Platform),
    'notes' : IDL.Text,
    'uploadTime' : IDL.Int,
    'evidenceType' : EvidenceType,
  });
  const ReasonCategory = IDL.Variant({
    'lowRating' : IDL.Null,
    'other' : IDL.Null,
    'documentsExpired' : IDL.Null,
    'fraudSuspicion' : IDL.Null,
    'selfieInvalid' : IDL.Null,
    'dangerousConduct' : IDL.Null,
    'multipleAccounts' : IDL.Null,
  });
  const Appeal = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'createdTime' : IDL.Int,
    'platform' : Platform,
    'userExplanation' : IDL.Text,
    'reasonCategory' : ReasonCategory,
    'generatedText' : IDL.Text,
    'evidenceIds' : IDL.Vec(IDL.Nat),
  });
  const PublicLossProfile = IDL.Record({
    'dailyEarnings' : IDL.Float64,
    'deactivationDate' : IDL.Int,
    'platform' : Platform,
    'daysPerWeek' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const CollectiveReport = IDL.Record({
    'region' : Region,
    'neighborhood' : IDL.Text,
    'platform' : Platform,
    'timestamp' : Time,
    'reason' : ReasonCategory,
  });
  const LossProfile = IDL.Record({
    'dailyEarnings' : IDL.Float64,
    'deactivationDate' : IDL.Int,
    'platform' : Platform,
    'daysPerWeek' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWeatherSample' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'temperatureC' : IDL.Float64,
            'condition' : WeatherCondition,
          }),
        ],
        [WorkSession],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvidence' : IDL.Func(
        [
          IDL.Record({
            'regiao' : IDL.Opt(Region),
            'bairro' : IDL.Opt(IDL.Text),
            'platform' : IDL.Opt(Platform),
            'notes' : IDL.Text,
            'evidenceType' : EvidenceType,
          }),
        ],
        [Evidence],
        [],
      ),
    'endWorkSession' : IDL.Func([IDL.Nat], [WorkSession], []),
    'generateAppeal' : IDL.Func(
        [
          IDL.Record({
            'platform' : Platform,
            'userExplanation' : IDL.Text,
            'reasonCategory' : ReasonCategory,
            'evidenceIds' : IDL.Vec(IDL.Nat),
          }),
        ],
        [Appeal],
        [],
      ),
    'getAllEvidence' : IDL.Func([], [IDL.Vec(Evidence)], ['query']),
    'getAppeal' : IDL.Func([IDL.Nat], [IDL.Opt(Appeal)], ['query']),
    'getCallerAppeals' : IDL.Func([], [IDL.Vec(Appeal)], ['query']),
    'getCallerLossProfile' : IDL.Func(
        [],
        [IDL.Opt(PublicLossProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectiveReports' : IDL.Func(
        [],
        [IDL.Vec(CollectiveReport)],
        ['query'],
      ),
    'getEvidenceById' : IDL.Func([IDL.Nat], [IDL.Opt(Evidence)], ['query']),
    'getEvidenceFiltered' : IDL.Func(
        [IDL.Opt(EvidenceType), IDL.Opt(Platform)],
        [IDL.Vec(Evidence)],
        ['query'],
      ),
    'getLossProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicLossProfile)],
        ['query'],
      ),
    'getPlatformStats' : IDL.Func([Platform], [IDL.Nat], ['query']),
    'getReasonStats' : IDL.Func([ReasonCategory], [IDL.Nat], ['query']),
    'getRegionStats' : IDL.Func([Region], [IDL.Nat], ['query']),
    'getRevisoMotivadaMessage' : IDL.Func([], [IDL.Text], ['query']),
    'getTimeline' : IDL.Func(
        [
          IDL.Record({
            'startTime' : IDL.Opt(IDL.Int),
            'endTime' : IDL.Opt(IDL.Int),
            'platformFilter' : IDL.Opt(Platform),
            'typeFilter' : IDL.Opt(EvidenceType),
          }),
        ],
        [IDL.Vec(Evidence)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkSession' : IDL.Func([IDL.Nat], [IDL.Opt(WorkSession)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkSession' : IDL.Func(
        [IDL.Record({ 'city' : IDL.Text })],
        [WorkSession],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setLossProfile' : IDL.Func([LossProfile], [], []),
    'submitCollectiveReport' : IDL.Func(
        [
          IDL.Record({
            'region' : Region,
            'neighborhood' : IDL.Text,
            'platform' : Platform,
            'reason' : ReasonCategory,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };