/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LossProfile {
  'dailyEarnings' : number,
  'deactivationDate' : bigint,
  'platform' : Platform,
  'daysPerWeek' : bigint,
}
export interface PagBankConfig {
  'webhookSecret' : [] | [string],
  'clientId' : [] | [string],
  'merchantId' : [] | [string],
  'enabled' : boolean,
  'clientSecret' : [] | [string],
}
export interface PagBankReturnWebhookUrlConfig {
  'returnUrl' : string,
  'webhookUrl' : string,
}
export interface PagBankTransparentCheckoutConfig {
  'token' : string,
  'publicKey' : string,
  'maxInstallments' : bigint,
  'email' : string,
  'interestRate' : [] | [number],
  'acceptedPaymentTypes' : Array<string>,
}
export interface PagBankWebhookPayload {
  'status' : string,
  'signature' : string,
  'paymentId' : string,
  'rawData' : string,
}
export interface PaymentCheckoutResponse {
  'paymentId' : string,
  'checkoutUrl' : [] | [string],
}
export interface PaymentConfig {
  'gatewayProvider' : PaymentProviderConfig,
  'pagbankProvider' : PagBankConfig,
}
export interface PaymentProviderConfig { 'enabled' : boolean }
export interface PaymentStatus {
  'status' : string,
  'paymentId' : string,
  'rawResponse' : string,
}
export type Platform = { 'uber' : null } |
  { 'ninetyNine' : null } |
  { 'ifood' : null } |
  { 'rappi' : null };
export type Principal = Principal;
export interface PublicPagBankConfig { 'enabled' : boolean }
export interface PublicPaymentConfig {
  'gatewayProvider' : PublicPaymentProviderConfig,
  'pagbankProvider' : PublicPagBankConfig,
}
export interface PublicPaymentProviderConfig { 'enabled' : boolean }
export type SubscriptionPlan = { 'free_24h' : null } |
  { 'pro_monthly' : null } |
  { 'pro_annual' : null };
export interface SubscriptionStatus {
  'startTime' : [] | [bigint],
  'endTime' : [] | [bigint],
  'currentPlan' : SubscriptionPlan,
}
export interface Testimonial {
  'id' : bigint,
  'status' : TestimonialStatus,
  'content' : string,
  'submitter' : Principal,
  'timestamp' : bigint,
}
export type TestimonialStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface UserAccessInfo {
  'principal' : Principal,
  'isBlockedByAdmin' : boolean,
  'subscriptionStatus' : SubscriptionStatus,
  'profile' : [] | [UserProfile],
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WeatherCondition = { 'cloudy' : null } |
  { 'clear' : null } |
  { 'nublado' : null } |
  { 'soleado' : null } |
  { 'tempestuoso' : null } |
  { 'windy' : null } |
  { 'rainy' : null };
export interface WeatherSample {
  'city' : string,
  'timestamp' : Time,
  'temperatureC' : number,
  'condition' : WeatherCondition,
}
export interface WorkSession {
  'id' : bigint,
  'startTime' : Time,
  'endTime' : [] | [Time],
  'owner' : Principal,
  'city' : string,
  'weatherSamples' : Array<WeatherSample>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkPaymentStatus' : ActorMethod<[string], PaymentStatus>,
  'createPagBankPaymentSession' : ActorMethod<
    [SubscriptionPlan],
    PaymentCheckoutResponse
  >,
  'createPaymentSession' : ActorMethod<
    [SubscriptionPlan],
    PaymentCheckoutResponse
  >,
  'getAllUserAccessInfo' : ActorMethod<[], Array<UserAccessInfo>>,
  'getApprovedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPagBankReturnWebhookUrls' : ActorMethod<
    [],
    [] | [PagBankReturnWebhookUrlConfig]
  >,
  'getPagBankTransparentCheckoutConfig' : ActorMethod<
    [],
    [] | [PagBankTransparentCheckoutConfig]
  >,
  'getPendingTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getPublicPaymentConfig' : ActorMethod<[], PublicPaymentConfig>,
  'getSubscriptionStatus' : ActorMethod<[], SubscriptionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'handlePagBankWebhook' : ActorMethod<[PagBankWebhookPayload], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logWorkSession' : ActorMethod<[{ 'city' : string }], WorkSession>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setLossProfile' : ActorMethod<[LossProfile], undefined>,
  'setPagBankReturnWebhookUrls' : ActorMethod<
    [PagBankReturnWebhookUrlConfig],
    undefined
  >,
  'setPagBankTransparentCheckoutConfig' : ActorMethod<
    [PagBankTransparentCheckoutConfig],
    undefined
  >,
  'setPaymentConfig' : ActorMethod<[PaymentConfig], undefined>,
  'submitTestimonial' : ActorMethod<[string], bigint>,
  'updateTestimonialStatus' : ActorMethod<
    [bigint, TestimonialStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];