/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    email?: string;
}
export interface Testimonial {
    id: bigint;
    status: TestimonialStatus;
    content: string;
    submitter: Principal;
    timestamp: bigint;
}
export interface PaymentConfig {
    gatewayProvider: PaymentProviderConfig;
    pagbankProvider: PagBankConfig;
}
export type Time = bigint;
export interface PublicPagBankConfig {
    enabled: boolean;
}
export interface PagBankTransparentCheckoutConfig {
    token: string;
    publicKey: string;
    maxInstallments: bigint;
    email: string;
    interestRate?: number;
    acceptedPaymentTypes: Array<string>;
}
export interface LossProfile {
    dailyEarnings: number;
    deactivationDate: bigint;
    platform: Platform;
    daysPerWeek: bigint;
}
export interface UserAccessInfo {
    principal: Principal;
    isBlockedByAdmin: boolean;
    subscriptionStatus: SubscriptionStatus;
    profile?: UserProfile;
}
export type Principal = Principal;
export interface PaymentProviderConfig {
    enabled: boolean;
}
export interface WeatherSample {
    city: string;
    timestamp: Time;
    temperatureC: number;
    condition: WeatherCondition;
}
export interface PublicPaymentConfig {
    gatewayProvider: PublicPaymentProviderConfig;
    pagbankProvider: PublicPagBankConfig;
}
export interface PagBankConfig {
    webhookSecret?: string;
    clientId?: string;
    merchantId?: string;
    enabled: boolean;
    clientSecret?: string;
}
export interface PaymentCheckoutResponse {
    paymentId: string;
    checkoutUrl?: string;
}
export interface PaymentStatus {
    status: string;
    paymentId: string;
    rawResponse: string;
}
export interface PagBankWebhookPayload {
    status: string;
    signature: string;
    paymentId: string;
    rawData: string;
}
export interface PagBankReturnWebhookUrlConfig {
    returnUrl: string;
    webhookUrl: string;
}
export interface SubscriptionStatus {
    startTime?: bigint;
    endTime?: bigint;
    currentPlan: SubscriptionPlan;
}
export interface PublicPaymentProviderConfig {
    enabled: boolean;
}
export interface WorkSession {
    id: bigint;
    startTime: Time;
    endTime?: Time;
    owner: Principal;
    city: string;
    weatherSamples: Array<WeatherSample>;
}
export enum Platform {
    uber = "uber",
    ninetyNine = "ninetyNine",
    ifood = "ifood",
    rappi = "rappi"
}
export enum SubscriptionPlan {
    free_24h = "free_24h",
    pro_monthly = "pro_monthly",
    pro_annual = "pro_annual"
}
export enum TestimonialStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WeatherCondition {
    cloudy = "cloudy",
    clear = "clear",
    nublado = "nublado",
    soleado = "soleado",
    tempestuoso = "tempestuoso",
    windy = "windy",
    rainy = "rainy"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkPaymentStatus(paymentId: string): Promise<PaymentStatus>;
    createPagBankPaymentSession(_plan: SubscriptionPlan): Promise<PaymentCheckoutResponse>;
    createPaymentSession(_plan: SubscriptionPlan): Promise<PaymentCheckoutResponse>;
    getAllUserAccessInfo(): Promise<Array<UserAccessInfo>>;
    getApprovedTestimonials(): Promise<Array<Testimonial>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPagBankReturnWebhookUrls(): Promise<PagBankReturnWebhookUrlConfig | null>;
    getPagBankTransparentCheckoutConfig(): Promise<PagBankTransparentCheckoutConfig | null>;
    getPendingTestimonials(): Promise<Array<Testimonial>>;
    getPublicPaymentConfig(): Promise<PublicPaymentConfig>;
    getSubscriptionStatus(): Promise<SubscriptionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    handlePagBankWebhook(payload: PagBankWebhookPayload): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    logWorkSession(params: {
        city: string;
    }): Promise<WorkSession>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setLossProfile(profile: LossProfile): Promise<void>;
    setPagBankReturnWebhookUrls(config: PagBankReturnWebhookUrlConfig): Promise<void>;
    setPagBankTransparentCheckoutConfig(config: PagBankTransparentCheckoutConfig): Promise<void>;
    setPaymentConfig(config: PaymentConfig): Promise<void>;
    submitTestimonial(content: string): Promise<bigint>;
    updateTestimonialStatus(testimonialId: bigint, newStatus: TestimonialStatus): Promise<void>;
}
import type { LossProfile as _LossProfile, PagBankConfig as _PagBankConfig, PagBankReturnWebhookUrlConfig as _PagBankReturnWebhookUrlConfig, PagBankTransparentCheckoutConfig as _PagBankTransparentCheckoutConfig, PaymentCheckoutResponse as _PaymentCheckoutResponse, PaymentConfig as _PaymentConfig, PaymentProviderConfig as _PaymentProviderConfig, Platform as _Platform, Principal as _Principal, SubscriptionPlan as _SubscriptionPlan, SubscriptionStatus as _SubscriptionStatus, Testimonial as _Testimonial, TestimonialStatus as _TestimonialStatus, Time as _Time, UserAccessInfo as _UserAccessInfo, UserProfile as _UserProfile, UserRole as _UserRole, WeatherCondition as _WeatherCondition, WeatherSample as _WeatherSample, WorkSession as _WorkSession } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkPaymentStatus(arg0: string): Promise<PaymentStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.checkPaymentStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkPaymentStatus(arg0);
            return result;
        }
    }
    async createPagBankPaymentSession(arg0: SubscriptionPlan): Promise<PaymentCheckoutResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createPagBankPaymentSession(to_candid_SubscriptionPlan_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PaymentCheckoutResponse_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPagBankPaymentSession(to_candid_SubscriptionPlan_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PaymentCheckoutResponse_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPaymentSession(arg0: SubscriptionPlan): Promise<PaymentCheckoutResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentSession(to_candid_SubscriptionPlan_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PaymentCheckoutResponse_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentSession(to_candid_SubscriptionPlan_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PaymentCheckoutResponse_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserAccessInfo(): Promise<Array<UserAccessInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserAccessInfo();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserAccessInfo();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedTestimonials();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedTestimonials();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPagBankReturnWebhookUrls(): Promise<PagBankReturnWebhookUrlConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPagBankReturnWebhookUrls();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPagBankReturnWebhookUrls();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPagBankTransparentCheckoutConfig(): Promise<PagBankTransparentCheckoutConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPagBankTransparentCheckoutConfig();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPagBankTransparentCheckoutConfig();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingTestimonials();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingTestimonials();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicPaymentConfig(): Promise<PublicPaymentConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicPaymentConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicPaymentConfig();
            return result;
        }
    }
    async getSubscriptionStatus(): Promise<SubscriptionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionStatus();
                return from_candid_SubscriptionStatus_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionStatus();
            return from_candid_SubscriptionStatus_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async handlePagBankWebhook(arg0: PagBankWebhookPayload): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handlePagBankWebhook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handlePagBankWebhook(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logWorkSession(arg0: {
        city: string;
    }): Promise<WorkSession> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkSession(arg0);
                return from_candid_WorkSession_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkSession(arg0);
            return from_candid_WorkSession_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setLossProfile(arg0: LossProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLossProfile(to_candid_LossProfile_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLossProfile(to_candid_LossProfile_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPagBankReturnWebhookUrls(arg0: PagBankReturnWebhookUrlConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPagBankReturnWebhookUrls(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPagBankReturnWebhookUrls(arg0);
            return result;
        }
    }
    async setPagBankTransparentCheckoutConfig(arg0: PagBankTransparentCheckoutConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPagBankTransparentCheckoutConfig(to_candid_PagBankTransparentCheckoutConfig_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPagBankTransparentCheckoutConfig(to_candid_PagBankTransparentCheckoutConfig_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPaymentConfig(arg0: PaymentConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentConfig(to_candid_PaymentConfig_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentConfig(to_candid_PaymentConfig_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitTestimonial(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimonial(arg0);
            return result;
        }
    }
    async updateTestimonialStatus(arg0: bigint, arg1: TestimonialStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonialStatus(arg0, to_candid_TestimonialStatus_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonialStatus(arg0, to_candid_TestimonialStatus_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_PagBankTransparentCheckoutConfig_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PagBankTransparentCheckoutConfig): PagBankTransparentCheckoutConfig {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentCheckoutResponse_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentCheckoutResponse): PaymentCheckoutResponse {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TestimonialStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestimonialStatus): TestimonialStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Testimonial_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimonial): Testimonial {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserAccessInfo_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAccessInfo): UserAccessInfo {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_WeatherCondition_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeatherCondition): WeatherCondition {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_WeatherSample_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeatherSample): WeatherSample {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_WorkSession_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkSession): WorkSession {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PagBankReturnWebhookUrlConfig]): PagBankReturnWebhookUrlConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PagBankTransparentCheckoutConfig]): PagBankTransparentCheckoutConfig | null {
    return value.length === 0 ? null : from_candid_PagBankTransparentCheckoutConfig_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _Principal;
    isBlockedByAdmin: boolean;
    subscriptionStatus: _SubscriptionStatus;
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    isBlockedByAdmin: boolean;
    subscriptionStatus: SubscriptionStatus;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        isBlockedByAdmin: value.isBlockedByAdmin,
        subscriptionStatus: from_candid_SubscriptionStatus_n11(_uploadFile, _downloadFile, value.subscriptionStatus),
        profile: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: [] | [bigint];
    endTime: [] | [bigint];
    currentPlan: _SubscriptionPlan;
}): {
    startTime?: bigint;
    endTime?: bigint;
    currentPlan: SubscriptionPlan;
} {
    return {
        startTime: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.startTime)),
        endTime: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.endTime)),
        currentPlan: from_candid_SubscriptionPlan_n14(_uploadFile, _downloadFile, value.currentPlan)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TestimonialStatus;
    content: string;
    submitter: _Principal;
    timestamp: bigint;
}): {
    id: bigint;
    status: TestimonialStatus;
    content: string;
    submitter: Principal;
    timestamp: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TestimonialStatus_n22(_uploadFile, _downloadFile, value.status),
        content: value.content,
        submitter: value.submitter,
        timestamp: value.timestamp
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    publicKey: string;
    maxInstallments: bigint;
    email: string;
    interestRate: [] | [number];
    acceptedPaymentTypes: Array<string>;
}): {
    token: string;
    publicKey: string;
    maxInstallments: bigint;
    email: string;
    interestRate?: number;
    acceptedPaymentTypes: Array<string>;
} {
    return {
        token: value.token,
        publicKey: value.publicKey,
        maxInstallments: value.maxInstallments,
        email: value.email,
        interestRate: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.interestRate)),
        acceptedPaymentTypes: value.acceptedPaymentTypes
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    endTime: [] | [_Time];
    owner: _Principal;
    city: string;
    weatherSamples: Array<_WeatherSample>;
}): {
    id: bigint;
    startTime: Time;
    endTime?: Time;
    owner: Principal;
    city: string;
    weatherSamples: Array<WeatherSample>;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.endTime)),
        owner: value.owner,
        city: value.city,
        weatherSamples: from_candid_vec_n34(_uploadFile, _downloadFile, value.weatherSamples)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    timestamp: _Time;
    temperatureC: number;
    condition: _WeatherCondition;
}): {
    city: string;
    timestamp: Time;
    temperatureC: number;
    condition: WeatherCondition;
} {
    return {
        city: value.city,
        timestamp: value.timestamp,
        temperatureC: value.temperatureC,
        condition: from_candid_WeatherCondition_n37(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentId: string;
    checkoutUrl: [] | [string];
}): {
    paymentId: string;
    checkoutUrl?: string;
} {
    return {
        paymentId: value.paymentId,
        checkoutUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.checkoutUrl))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    free_24h: null;
} | {
    pro_monthly: null;
} | {
    pro_annual: null;
}): SubscriptionPlan {
    return "free_24h" in value ? SubscriptionPlan.free_24h : "pro_monthly" in value ? SubscriptionPlan.pro_monthly : "pro_annual" in value ? SubscriptionPlan.pro_annual : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): TestimonialStatus {
    return "pending" in value ? TestimonialStatus.pending : "approved" in value ? TestimonialStatus.approved : "rejected" in value ? TestimonialStatus.rejected : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cloudy: null;
} | {
    clear: null;
} | {
    nublado: null;
} | {
    soleado: null;
} | {
    tempestuoso: null;
} | {
    windy: null;
} | {
    rainy: null;
}): WeatherCondition {
    return "cloudy" in value ? WeatherCondition.cloudy : "clear" in value ? WeatherCondition.clear : "nublado" in value ? WeatherCondition.nublado : "soleado" in value ? WeatherCondition.soleado : "tempestuoso" in value ? WeatherCondition.tempestuoso : "windy" in value ? WeatherCondition.windy : "rainy" in value ? WeatherCondition.rainy : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimonial>): Array<Testimonial> {
    return value.map((x)=>from_candid_Testimonial_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeatherSample>): Array<WeatherSample> {
    return value.map((x)=>from_candid_WeatherSample_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserAccessInfo>): Array<UserAccessInfo> {
    return value.map((x)=>from_candid_UserAccessInfo_n9(_uploadFile, _downloadFile, x));
}
function to_candid_LossProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LossProfile): _LossProfile {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_PagBankConfig_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PagBankConfig): _PagBankConfig {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_PagBankTransparentCheckoutConfig_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PagBankTransparentCheckoutConfig): _PagBankTransparentCheckoutConfig {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentConfig_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentConfig): _PaymentConfig {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_Platform_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionPlan_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): _SubscriptionPlan {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TestimonialStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestimonialStatus): _TestimonialStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dailyEarnings: number;
    deactivationDate: bigint;
    platform: Platform;
    daysPerWeek: bigint;
}): {
    dailyEarnings: number;
    deactivationDate: bigint;
    platform: _Platform;
    daysPerWeek: bigint;
} {
    return {
        dailyEarnings: value.dailyEarnings,
        deactivationDate: value.deactivationDate,
        platform: to_candid_Platform_n43(_uploadFile, _downloadFile, value.platform),
        daysPerWeek: value.daysPerWeek
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    publicKey: string;
    maxInstallments: bigint;
    email: string;
    interestRate?: number;
    acceptedPaymentTypes: Array<string>;
}): {
    token: string;
    publicKey: string;
    maxInstallments: bigint;
    email: string;
    interestRate: [] | [number];
    acceptedPaymentTypes: Array<string>;
} {
    return {
        token: value.token,
        publicKey: value.publicKey,
        maxInstallments: value.maxInstallments,
        email: value.email,
        interestRate: value.interestRate ? candid_some(value.interestRate) : candid_none(),
        acceptedPaymentTypes: value.acceptedPaymentTypes
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gatewayProvider: PaymentProviderConfig;
    pagbankProvider: PagBankConfig;
}): {
    gatewayProvider: _PaymentProviderConfig;
    pagbankProvider: _PagBankConfig;
} {
    return {
        gatewayProvider: value.gatewayProvider,
        pagbankProvider: to_candid_PagBankConfig_n49(_uploadFile, _downloadFile, value.pagbankProvider)
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    webhookSecret?: string;
    clientId?: string;
    merchantId?: string;
    enabled: boolean;
    clientSecret?: string;
}): {
    webhookSecret: [] | [string];
    clientId: [] | [string];
    merchantId: [] | [string];
    enabled: boolean;
    clientSecret: [] | [string];
} {
    return {
        webhookSecret: value.webhookSecret ? candid_some(value.webhookSecret) : candid_none(),
        clientId: value.clientId ? candid_some(value.clientId) : candid_none(),
        merchantId: value.merchantId ? candid_some(value.merchantId) : candid_none(),
        enabled: value.enabled,
        clientSecret: value.clientSecret ? candid_some(value.clientSecret) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): {
    free_24h: null;
} | {
    pro_monthly: null;
} | {
    pro_annual: null;
} {
    return value == SubscriptionPlan.free_24h ? {
        free_24h: null
    } : value == SubscriptionPlan.pro_monthly ? {
        pro_monthly: null
    } : value == SubscriptionPlan.pro_annual ? {
        pro_annual: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): {
    uber: null;
} | {
    ninetyNine: null;
} | {
    ifood: null;
} | {
    rappi: null;
} {
    return value == Platform.uber ? {
        uber: null
    } : value == Platform.ninetyNine ? {
        ninetyNine: null
    } : value == Platform.ifood ? {
        ifood: null
    } : value == Platform.rappi ? {
        rappi: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestimonialStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == TestimonialStatus.pending ? {
        pending: null
    } : value == TestimonialStatus.approved ? {
        approved: null
    } : value == TestimonialStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
